#!/usr/bin/env bash
#how display listening port.
#Write a Bash script that displays listening ports:

    #That only shows listening sockets.
    #That shows the PID and name of the program to which each socket belongs.
netstat -ip
