#!/usr/bin/env bash
#script displays numbers from 1 to 20.

counter=1
while [ $counter -lt 21 ]
do
   case $counter in

       4)
         echo $counter
         echo "bad luck from china"
         ;;

      9)
         echo $counter
         echo "bad luck from japan"
         ;;
     17)
         echo $counter
         echo "bad luck from italy"
         ;;
      *) 
         echo $counter
         ;;
   esac
   let counter+=1
done
